/**
 * dsh-restart-plugin — host half.
 *
 * Publishes four small `/api/dsh-restart/*` routes and performs the restart
 * they ask for: this DSH process exits, and a fresh one starts with the very
 * command line and working directory this process was launched with.
 *
 * The browser half needs one thing more than "is it up yet": every DSH boot
 * mints a NEW launch token (`connection.authenticatedUrl`) that the app's own
 * channel is authenticated with, so an already-open page cannot simply
 * reconnect to the replacement — its token belongs to the dead process. These
 * routes therefore hand the CURRENT process's token to the page (plain `/api`
 * routes are reachable without one), and the page navigates back with it.
 * Without that, a page keeps rendering while every app-channel call fails,
 * which is what silently breaks other client plugins' live features until the
 * page is reopened.
 *
 * Why a helper process instead of the harness process seams: every process the
 * harness starts is owned by a provider that puts it in a Job Object with
 * `JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE`, so anything spawned through those seams
 * is terminated together with DSH — it could never start the replacement. This
 * plugin therefore uses Node's own `child_process` directly: one detached,
 * windowless helper that survives this process, waits for it to exit, and only
 * then launches the replacement (which also keeps the listen port free).
 *
 * @module dsh-restart-plugin
 */
import { spawn } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { homedir, tmpdir } from 'node:os'
import { dirname, join } from 'node:path'

/** Stable Cordis plugin name. */
export const name = 'dsh-restart-plugin'

/** The browser carrier is the only hard dependency; the rest is optional. */
export const inject = ['webServer']

/** Route prefix. Plain `/api` routes stay reachable from a page whose token is stale. */
const ROUTE_PREFIX = '/api/dsh-restart'

/**
 * Identity of this DSH process. The browser polls `ping` after a restart and
 * waits for a value different from the one it saw before, which is the only
 * reliable "the new process is really up" signal (the old socket can still
 * answer for a moment while the tree unwinds).
 */
const BOOT_ID = `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`

/** Grace between answering the browser and starting the shutdown. */
const SHUTDOWN_DELAY_MS = 400

/** Forced exit if the graceful shutdown has not finished by then. */
const FORCE_EXIT_MS = 6000

/** Node's `--no-open` equivalent: never let a restart pop a second browser tab. */
const NO_OPEN_FLAG = '--no-open'

/** Absolute path of the generated helper script. */
const SHIM_PATH = join(tmpdir(), 'dsh-restart-shim.mjs')

/**
 * The helper: wait for a process id to disappear, then start a command again,
 * detached, with its output appended to a log file.
 *
 * Arguments after the script path are: `<pid> <cwd> <logPath> <command> [args…]`.
 * `pid` 0 skips the wait (the self-test uses it to prove the mechanism without
 * stopping anything). `stdio: 'ignore'` keeps it silent and windowless; the
 * reparented replacement inherits this helper's own stdio disposition, never
 * DSH's.
 */
export const SHIM_SOURCE = [
  '// Generated by dsh-restart-plugin. Safe to delete; it is rewritten on every restart.',
  "import { spawn } from 'node:child_process'",
  "import { openSync } from 'node:fs'",
  "import { setTimeout as sleep } from 'node:timers/promises'",
  '',
  'const [, , pidArg, cwd, logPath, command, ...args] = process.argv',
  'const pid = Number(pidArg)',
  'const stillAlive = () => {',
  '  try { process.kill(pid, 0); return true } catch (error) {',
  "    return error !== null && typeof error === 'object' && error.code === 'EPERM'",
  '  }',
  '}',
  'if (pid > 0) {',
  '  for (let i = 0; i < 900 && stillAlive(); i += 1) await sleep(100)',
  '  await sleep(400)',
  '}',
  "let out = 'ignore'",
  "let err = 'ignore'",
  "try { const fd = openSync(logPath, 'a'); out = fd; err = fd } catch { /* keep the run silent */ }",
  'const child = spawn(command, args, {',
  '  cwd,',
  '  detached: true,',
  "  stdio: ['ignore', out, err],",
  '  windowsHide: true,',
  '  env: process.env,',
  '})',
  'child.unref()',
  '',
].join('\n')

/** Marker file the self-test writes through a detached helper. */
const SELFTEST_MARKER = join(tmpdir(), 'dsh-restart-selftest.txt')

/** Replacement program for the self-test: append one line, then exit. */
const SELFTEST_SCRIPT = `require('node:fs').appendFileSync(${JSON.stringify(SELFTEST_MARKER)}, new Date().toISOString() + ' detached helper ran inside ' + process.pid + '\\n')`

/** The Harness home, matching the launcher's own resolution. */
function dshHome() {
  const configured = process.env.DSH_HOME
  return configured !== undefined && configured !== '' ? configured : join(homedir(), '.dsh')
}

/** Quote one argument for display only. */
function quote(argument) {
  return /[\s"]/u.test(argument) ? `"${argument}"` : argument
}

/**
 * The exact relaunch recipe: this Node binary, this DSH entry script, and this
 * invocation's own app arguments.
 *
 * `--no-open` is added when the running invocation did not carry it, because
 * the web app opens the UI in the default browser by default — a restart must
 * not leave the user with a second tab next to the page they are already on.
 *
 * @returns the command, its arguments, and a printable form, or an error string.
 */
function relaunchRecipe() {
  const entry = process.argv[1]
  if (typeof entry !== 'string' || entry === '' || !existsSync(entry)) {
    return { error: `cannot locate the running DSH entry script (process.argv[1] = ${String(entry)})` }
  }
  const args = process.argv.slice(2)
  if (!args.includes(NO_OPEN_FLAG)) args.push(NO_OPEN_FLAG)
  const printable = [process.execPath, entry, ...args].map(quote).join(' ')
  return { command: process.execPath, args: [entry, ...args], printable }
}

/** Write the helper and start it detached, so it outlives this process. */
function startHelper(recipe) {
  mkdirSync(dirname(SHIM_PATH), { recursive: true })
  writeFileSync(SHIM_PATH, SHIM_SOURCE, 'utf8')
  const logPath = join(dshHome(), 'dsh-restart.log')
  mkdirSync(dirname(logPath), { recursive: true })
  const helper = spawn(
    process.execPath,
    [SHIM_PATH, String(process.pid), process.cwd(), logPath, recipe.command, ...recipe.args],
    { detached: true, stdio: 'ignore', windowsHide: true, cwd: tmpdir(), env: process.env },
  )
  helper.unref()
  return { helperPid: helper.pid, logPath }
}

/** One JSON reply. */
function sendJson(res, status, body) {
  const text = JSON.stringify(body)
  res.statusCode = status
  res.setHeader('content-type', 'application/json; charset=utf-8')
  res.setHeader('cache-control', 'no-store')
  res.end(text)
}

/**
 * Register the restart routes.
 * @param ctx - the plugin context carrying the web server.
 */
export function apply(ctx) {
  const webServer = ctx.webServer
  let scheduled = false

  /**
   * The launcher's own readiness bit. The browser half navigates back only once
   * this process reports ready, so it never re-boots the page against a tree
   * that is still mounting its client rows.
   */
  let bootReady = false
  const appReady = ctx.get('appReady')
  if (appReady !== undefined && typeof appReady.onReady === 'function') {
    ctx.effect(() => appReady.onReady(() => {
      bootReady = true
    }))
  }

  /**
   * This process's launch token, read per request: the `connection` service may
   * mount after this row, and this token is what a stale page must present to
   * become a valid client of THIS process again.
   * @returns the token, or null when the connection service is unavailable.
   */
  const launchToken = () => {
    const connection = ctx.get('connection')
    if (connection === undefined || typeof connection.authenticatedUrl !== 'function') return null
    try {
      const url = new URL(connection.authenticatedUrl(`http://127.0.0.1:${String(webServer.port)}`))
      return url.searchParams.get('token')
    } catch {
      return null
    }
  }

  const status = () => {
    const recipe = relaunchRecipe()
    return {
      ok: recipe.error === undefined,
      bootId: BOOT_ID,
      ready: bootReady,
      token: launchToken(),
      pid: process.pid,
      cwd: process.cwd(),
      command: recipe.printable ?? null,
      logPath: join(dshHome(), 'dsh-restart.log'),
      error: recipe.error ?? null,
    }
  }

  /**
   * Answer first, then shut down: the browser needs the old `bootId` before the
   * socket disappears, otherwise it cannot tell the new process from the old one.
   */
  const restart = (res) => {
    if (scheduled) {
      sendJson(res, 200, { ok: true, bootId: BOOT_ID, alreadyScheduled: true })
      return
    }
    const recipe = relaunchRecipe()
    if (recipe.error !== undefined) {
      sendJson(res, 500, { ok: false, error: recipe.error })
      return
    }
    let started
    try {
      started = startHelper(recipe)
    } catch (error) {
      sendJson(res, 500, { ok: false, error: `failed to start the restart helper: ${String(error && error.message ? error.message : error)}` })
      return
    }
    scheduled = true
    sendJson(res, 200, {
      ok: true,
      bootId: BOOT_ID,
      scheduled: true,
      helperPid: started.helperPid,
      command: recipe.printable,
      logPath: started.logPath,
    })

    // Plain globals on purpose: the timer service would be disposed by the very
    // shutdown it schedules. `appExit` is the launcher's graceful path (dispose
    // the tree, then drain); the unref'd backstop only fires if that drains short.
    setTimeout(() => {
      const exit = ctx.get('appExit')
      if (typeof exit === 'function') {
        try {
          exit(0)
          setTimeout(() => process.exit(0), FORCE_EXIT_MS).unref()
          return
        } catch {
          /* fall through to the hard exit */
        }
      }
      process.exit(0)
    }, SHUTDOWN_DELAY_MS)
  }

  ctx.effect(() =>
    webServer.register({
      kind: 'exact',
      path: `${ROUTE_PREFIX}/status`,
      handler: (_req, res) => sendJson(res, 200, status()),
    }),
  )

  ctx.effect(() =>
    webServer.register({
      kind: 'exact',
      path: `${ROUTE_PREFIX}/ping`,
      handler: (_req, res) => sendJson(res, 200, {
        ok: true,
        bootId: BOOT_ID,
        ready: bootReady,
        token: launchToken(),
        pid: process.pid,
      }),
    }),
  )

  ctx.effect(() =>
    webServer.register({
      kind: 'exact',
      path: `${ROUTE_PREFIX}/selftest`,
      handler: (req, res) => {
        if (req.method !== 'POST') {
          sendJson(res, 405, { ok: false, error: 'use POST' })
          return
        }
        try {
          mkdirSync(dirname(SHIM_PATH), { recursive: true })
          writeFileSync(SHIM_PATH, SHIM_SOURCE, 'utf8')
          const logPath = join(dshHome(), 'dsh-restart.log')
          const helper = spawn(
            process.execPath,
            [SHIM_PATH, '0', tmpdir(), logPath, process.execPath, '-e', SELFTEST_SCRIPT],
            { detached: true, stdio: 'ignore', windowsHide: true, cwd: tmpdir(), env: process.env },
          )
          helper.unref()
          sendJson(res, 200, { ok: true, helperPid: helper.pid, marker: SELFTEST_MARKER, logPath })
        } catch (error) {
          sendJson(res, 500, { ok: false, error: String(error && error.message ? error.message : error) })
        }
      },
    }),
  )

  ctx.effect(() =>
    webServer.register({
      kind: 'exact',
      path: `${ROUTE_PREFIX}/restart`,
      handler: (req, res) => {
        if (req.method !== 'POST') {
          sendJson(res, 405, { ok: false, error: 'use POST' })
          return
        }
        restart(res)
      },
    }),
  )
}
